import 'package:flutter/material.dart';
import '../../../petrol_pump/domain/entities/petrol_pump.dart';
import '../providers/admin_provider.dart';

class AdminPumpFormScreen extends StatefulWidget {
  final AdminProvider provider; final PetrolPump? pump;
  const AdminPumpFormScreen({super.key, required this.provider, this.pump});
  @override State<AdminPumpFormScreen> createState()=>_AdminPumpFormScreenState();
}
class _AdminPumpFormScreenState extends State<AdminPumpFormScreen> {
  final _form=GlobalKey<FormState>(); late final TextEditingController name,address,lat,lng,phone,rating,reviews,hours,logo,fuel,prices;
  bool open=true;
  @override void initState(){super.initState();final p=widget.pump; name=TextEditingController(text:p?.name);address=TextEditingController(text:p?.address);lat=TextEditingController(text:p?.latitude.toString());lng=TextEditingController(text:p?.longitude.toString());phone=TextEditingController(text:p?.phone);rating=TextEditingController(text:p?.rating.toString());reviews=TextEditingController(text:p?.reviewCount.toString());hours=TextEditingController(text:p?.openingHours);logo=TextEditingController(text:p?.logoUrl);fuel=TextEditingController(text:p?.fuelTypes.join(', ')); prices=TextEditingController(text:p?.fuelPrices.entries.map((e)=>'${e.key}:${e.value}').join(', '));open=p?.isOpen??true;}
  @override void dispose(){for(final c in [name,address,lat,lng,phone,rating,reviews,hours,logo,fuel,prices]){c.dispose();}super.dispose();}
  String? req(String? v)=>v==null||v.trim().isEmpty?'Required':null;
  Widget field(TextEditingController c,String label,{TextInputType? type,String? Function(String?)? validator})=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextFormField(controller:c,keyboardType:type,validator:validator??req,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
  Map<String,double> _parsePrices(String value){ final result=<String,double>{}; for(final part in value.split(',')){ final bits=part.split(':'); if(bits.length==2){ final price=double.tryParse(bits[1].trim()); if(price!=null && price>=0) result[bits[0].trim()]=price; }} return result; }
  Future<void> save() async {if(!_form.currentState!.validate())return; final data={'name':name.text.trim(),'address':address.text.trim(),'latitude':double.parse(lat.text),'longitude':double.parse(lng.text),'phone':phone.text.trim().isEmpty?null:phone.text.trim(),'rating':double.tryParse(rating.text)??0,'review_count':int.tryParse(reviews.text)??0,'is_open':open,'opening_hours':hours.text.trim().isEmpty?null:hours.text.trim(),'logo_url':logo.text.trim().isEmpty?null:logo.text.trim(),'fuel_types':fuel.text.split(',').map((e)=>e.trim()).where((e)=>e.isNotEmpty).toList(),'fuel_prices':_parsePrices(prices.text)}; final ok=widget.pump==null?await widget.provider.add(data):await widget.provider.edit(widget.pump!.id,data); if(ok&&mounted)Navigator.pop(context);}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.pump==null?'Add Pump':'Edit Pump'),actions:[IconButton(onPressed:save,icon:const Icon(Icons.save))]),body:Form(key:_form,child:ListView(padding:const EdgeInsets.all(16),children:[field(name,'Name'),field(address,'Address'),Row(children:[Expanded(child:field(lat,'Latitude',type:const TextInputType.numberWithOptions(decimal:true))),const SizedBox(width:12),Expanded(child:field(lng,'Longitude',type:const TextInputType.numberWithOptions(decimal:true)))]),field(phone,'Phone',type:TextInputType.phone,validator:(_)=>null),Row(children:[Expanded(child:field(rating,'Rating',type:const TextInputType.numberWithOptions(decimal:true),validator:(_)=>null)),const SizedBox(width:12),Expanded(child:field(reviews,'Review Count',type:TextInputType.number,validator:(_)=>null))]),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Open Now'),value:open,onChanged:(v)=>setState(()=>open=v)),field(hours,'Opening Hours',validator:(_)=>null),field(fuel,'Fuel Types (comma separated)',validator:(_)=>null),field(prices,'Fuel Prices (e.g. Petrol:120, Diesel:110)',validator:(_)=>null),field(logo,'Logo URL',validator:(_)=>null),const SizedBox(height:8),FilledButton.icon(onPressed:save,icon:const Icon(Icons.save),label:Text(widget.pump==null?'Add Pump':'Save Changes'))])));
}
